import dayjs from 'dayjs/esm';
import { IInterfacing } from 'app/entities/interfacing/interfacing.model';
import { IModel } from 'app/entities/model/model.model';
import { IDeviceCategory } from 'app/entities/device-category/device-category.model';
import { IDeviceType } from 'app/entities/device-type/device-type.model';
import { IFormula } from 'app/entities/formula/formula.model';
import { IIsland } from 'app/entities/island/island.model';
import { ICurrencyType } from 'app/entities/currency-type/currency-type.model';

export interface IDevice {
  id: string;
  serial?: string | null;
  isProtocolEsdcs?: boolean | null;
  numberPlayedReport?: number | null;
  sasDenomination?: number | null;
  isMultigame?: boolean | null;
  isMultiDenomination?: boolean | null;
  isRetanqueo?: boolean | null;
  state?: string | null;
  theoreticalHold?: number | null;
  sasIdentifier?: number | null;
  creditLimit?: number | null;
  hasHooper?: boolean | null;
  coljuegosCode?: string | null;
  fabricationDate?: dayjs.Dayjs | null;
  currentToken?: number | null;
  denominationTito?: number | null;
  endLostCommunication?: dayjs.Dayjs | null;
  startLostCommunication?: dayjs.Dayjs | null;
  reportMultiplier?: number | null;
  nuid?: string | null;
  payManualPrize?: boolean | null;
  manualHandpay?: boolean | null;
  manualJackpot?: boolean | null;
  manualGameEvent?: boolean | null;
  betCode?: string | null;
  homologationIndicator?: boolean | null;
  coljuegosModel?: string | null;
  reportable?: boolean | null;
  aftDenomination?: number | null;
  lastUpdateDate?: dayjs.Dayjs | null;
  enableRollover?: boolean | null;
  lastCorruptionDate?: dayjs.Dayjs | null;
  daftDenomination?: number | null;
  prizesEnabled?: boolean | null;
  idInterfacing?: Pick<IInterfacing, 'id'> | null;
  idModel?: Pick<IModel, 'id'> | null;
  idDeviceCategory?: Pick<IDeviceCategory, 'id'> | null;
  idDeviceType?: Pick<IDeviceType, 'id'> | null;
  idFormulaHandpay?: Pick<IFormula, 'id'> | null;
  idFormulaJackpot?: Pick<IFormula, 'id'> | null;
  idIsland?: Pick<IIsland, 'id'> | null;
  idCurrencyType?: Pick<ICurrencyType, 'id'> | null;
}

export type NewDevice = Omit<IDevice, 'id'> & { id: null };
